### ISSUE TITLE
Error on every group created

### ISSUE THREAD

**Issue by maesben** [Martin-Day/Auto-Create-Dynamic-Security-Groups#1]
Thanks for this script, it's exactly what I'm looking for to create a dynamic group based on department (in my case, department is the class and the users are students). However, when running, I get the same error 40 times (once for each group, i.e. class, it tries to make). Any advice?

New-AzureADMSGroup : A parameter cannot be found that matches parameter name 'MembershipRuleProcessingState'.
At line:18 char:30
+     $dg = New-AzureADMSGroup @args
+                              ~~~~~
    + CategoryInfo          : InvalidArgument: (:) [New-AzureADMSGroup], ParameterBindingException
    + FullyQualifiedErrorId : NamedParameterNotFound,Microsoft.Open.MSGraphV10.PowerShell.NewMSGroup

**Comment by maesben** [comment]
Found the problem myself. I had to install the preview version of AzureAD (see here: https://github.com/MicrosoftDocs/azure-docs/issues/34263)

**Comment by Martin-Day** [comment]
> Found the problem myself. I had to install the preview version of AzureAD (see here: [MicrosoftDocs/azure-docs#34263](https://github.com/MicrosoftDocs/azure-docs/issues/34263))

Glad you were able to solve the problem, I appreciate you letting me know 😊
